const transViewTypes = {
  CHANGE_FILTER: 'TRANSVIEW_CHANGE_FILTER',
  CHANGE_SORT_METHOD: 'TRANSVIEW_CHANGE_SORT_METHOD',

  EDITING_ON: 'TRANSVIEW_EDITING_ON',
  EDITING_OFF: 'TRANSVIEW_EDITING_FALSE',
}

export default transViewTypes;