const transactionTypes = {
  SUCCESS_GET_TRANSACTIONS: 'TRANSACTION_SUCCESS_GET',
  ERROR_GET_TRANSACTIONS: 'TRANSACTION_ERROR_GET',

  SUCCESS_CREATE_TRANSATCION: 'TRANSACTION_SUCCESS_CREATE',
  ERROR_CREATE_TRANSACTION: 'TRANSACTION_ERROR_CREATE',

  SUCCESS_DELETE_TRANSACTION: 'TRANSACTION_SUCCESS_DELETE',
  ERROR_DELETE_TRANSACTION: 'TRANSACTION_ERROR_DELETE',
}

export default transactionTypes;