# Generated by Django 3.0.8 on 2020-07-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20200728_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='transactions', to='finances.UserTag'),
        ),
    ]
